#!/bin/bash
# =============================================================
# 将軍システム v7.0 - Monthly Maintenance (反省会) Setup
# =============================================================
# 月次メンテナンスの cron 設定スクリプト。
# CT 100 (本陣) で実行。
#
# Usage: bash maintenance.sh [install|uninstall|run|status]
# =============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
VENV_DIR="${PROJECT_DIR}/.venv"
MAINTENANCE_SCRIPT="${PROJECT_DIR}/setup/run_maintenance.sh"
LOG_DIR="${PROJECT_DIR}/logs"
CRON_JOB="0 9 1 * * ${MAINTENANCE_SCRIPT} >> ${LOG_DIR}/maintenance.log 2>&1"

# Create maintenance runner script
create_runner() {
    mkdir -p "${LOG_DIR}"
    mkdir -p "${PROJECT_DIR}/reports/maintenance"

    cat > "$MAINTENANCE_SCRIPT" << RUNNER
#!/bin/bash
# 将軍システム - Monthly Maintenance Runner
# Auto-generated by maintenance.sh

set -euo pipefail

PROJECT_DIR="${PROJECT_DIR}"
VENV_DIR="${VENV_DIR}"

echo "========================================"
echo "将軍システム 月次メンテナンス (反省会)"
echo "実行日時: \$(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"

# Activate venv
if [ -f "\${VENV_DIR}/bin/activate" ]; then
    source "\${VENV_DIR}/bin/activate"
else
    echo "ERROR: venv not found at \${VENV_DIR}"
    exit 1
fi

cd "\$PROJECT_DIR"

# Run maintenance
python -m shogun.cli maintenance run

echo ""
echo "========================================"
echo "メンテナンス完了: \$(date '+%Y-%m-%d %H:%M:%S')"
echo "========================================"
RUNNER

    chmod +x "$MAINTENANCE_SCRIPT"
    echo "  作成: ${MAINTENANCE_SCRIPT}"
}

install_cron() {
    create_runner

    # Check if already installed
    if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
        echo "  cron 既に設定済み"
        return
    fi

    # Add cron job
    (crontab -l 2>/dev/null; echo "$CRON_JOB") | crontab -
    echo "  cron 設定完了: 毎月1日 9:00 JST"
}

uninstall_cron() {
    if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
        crontab -l | grep -v "run_maintenance.sh" | crontab -
        echo "  cron 削除完了"
    else
        echo "  cron 設定なし"
    fi
}

show_status() {
    echo "月次メンテナンス設定状況:"
    echo ""

    # Check runner script
    if [ -f "$MAINTENANCE_SCRIPT" ]; then
        echo "  ✓ 実行スクリプト: ${MAINTENANCE_SCRIPT}"
    else
        echo "  ✗ 実行スクリプト: 未作成"
    fi

    # Check cron
    if crontab -l 2>/dev/null | grep -q "run_maintenance.sh"; then
        echo "  ✓ cron: 設定済み (毎月1日 9:00)"
    else
        echo "  ✗ cron: 未設定"
    fi

    # Check log directory
    if [ -d "$LOG_DIR" ]; then
        echo "  ✓ ログディレクトリ: ${LOG_DIR}"
    else
        echo "  ✗ ログディレクトリ: 未作成"
    fi

    # Check reports directory
    REPORTS_DIR="${PROJECT_DIR}/reports/maintenance"
    if [ -d "$REPORTS_DIR" ]; then
        REPORT_COUNT=$(ls -1 "$REPORTS_DIR"/*.json 2>/dev/null | wc -l || echo "0")
        echo "  ✓ レポート: ${REPORT_COUNT}件 (${REPORTS_DIR})"
    else
        echo "  ✗ レポートディレクトリ: 未作成"
    fi

    # Next maintenance
    echo ""
    if [ -f "${VENV_DIR}/bin/activate" ]; then
        source "${VENV_DIR}/bin/activate"
        cd "$PROJECT_DIR"
        python -c "
from shogun.core.maintenance import MaintenanceManager
m = MaintenanceManager()
next_date = m.get_next_maintenance_date()
print(f'  次回メンテナンス: {next_date.strftime(\"%Y-%m-%d %H:%M\")}')
" 2>/dev/null || echo "  次回メンテナンス: 計算不可"
    fi
}

run_now() {
    if [ ! -f "$MAINTENANCE_SCRIPT" ]; then
        create_runner
    fi
    echo "メンテナンスを実行します..."
    bash "$MAINTENANCE_SCRIPT"
}

# ─── Main ───

case "${1:-status}" in
    install)
        echo "月次メンテナンス cron インストール..."
        install_cron
        echo ""
        show_status
        ;;
    uninstall)
        echo "月次メンテナンス cron アンインストール..."
        uninstall_cron
        ;;
    run)
        run_now
        ;;
    status)
        show_status
        ;;
    *)
        echo "Usage: $0 [install|uninstall|run|status]"
        echo ""
        echo "  install    cron 設定 (毎月1日 9:00)"
        echo "  uninstall  cron 削除"
        echo "  run        今すぐ実行"
        echo "  status     設定状況確認"
        exit 1
        ;;
esac
